name: Build and deploy Node.js app to Azure Web App - my-backend-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run build and tests (optional)
        working-directory: ./backend
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for Azure login
      contents: read   # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB3C5EA18E6F4283B7F497CBAE12A9E4 }}           
           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1D5B92ED92344E2E89747CE213DB7C85 }}  
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B52498B7D91C444095BE54D825A5BC8A }} 
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-backend-api'
          slot-name: 'Production'
          package: ./backend
